### ISSUE TITLE
Is the minimum Ansible version really 1.2?

### ISSUE THREAD

**Issue by efine** [tnewman/kazoo-ansible#3]
**Bottom line**: What is the tested minimum version?

In this repository, there is no mention of minimum ansible version, but in the meta directories on the other repositories like `kazoo-ansible/freeswitch`, it claims the minimum version is 1.2.

- Is that true? 
- Which Ansible version are you actually testing with? I may have missed it, but you don't mention the actual Ansible installation in your installation guide.

FWIW, my Ansible installation went something like this:

```
$ virtualenv --python=python2.7 .env
$ source .env/bin/activate
(.env) $ pip install ansible
<lots of stuff>
(.env) $ pip freeze | grep ansible
ansible==2.4.1.0
(.env) $ deactivate
$
```

I ask this because I have some potential future pull requests for these scripts, but they are based on Ansible 2.4 and I've tested only on 2.4. I could "downgrade" but that would mean changing much of what I have. Suggestions welcome.

**Comment by efine** [comment]
I see you are installing ansible from the distro. If your distro is Centos 7 or RHEL 7, it seems as if they provide Ansible 2.4.0.0:

```
#  yum info ansible | grep Version
Version     : 2.4.0.0
```

So you're probably using 2.4?

**Comment by tnewman** [comment]
Yup. It's 2.4, and you have to use CentOS 7. No other OSs are supported.

**Comment by tnewman** [comment]
I updated the installation guide to reference this fact: https://github.com/kazoo-ansible/kazoo-ansible/blob/master/INSTALL.md

**Comment by efine** [comment]
Don't you want to specify Ansible >= 2.4 in the guide?
